In [1]:
my_list = [1,2,3]

In [2]:
import numpy as np

In [3]:
arr = np.array(my_list)

In [6]:
arr

array([1, 2, 3])

In [7]:
my_mat = [[1,2,3],[4,5,6],[7,8,9]]

In [8]:
np.array(my_mat)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [11]:
np.arange(0,31,3)

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27, 30])

In [16]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [17]:
np.ones((4,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [28]:
np.linspace(0,100,5)

array([  0.,  25.,  50.,  75., 100.])

In [30]:
np.eye(7)

array([[1., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 1.]])

In [39]:
np.random.rand(5,4)

array([[0.08409979, 0.58406446, 0.41752383, 0.89022461],
       [0.00371895, 0.912676  , 0.13537199, 0.54425371],
       [0.96426712, 0.1343315 , 0.45135233, 0.61961577],
       [0.1407295 , 0.8422583 , 0.4248573 , 0.09370549],
       [0.38805921, 0.81497425, 0.08059481, 0.91777517]])

In [24]:
np.random.randn(3,3)

array([[-0.19631834, -0.24061962,  0.98947478],
       [-0.24990347, -0.61105091, -2.11572205],
       [-0.04154842,  0.80869242, -0.98220522]])

In [45]:
np.random.randint(1,21,(4,4))

array([[ 5, 11,  3, 14],
       [20, 11,  7, 10],
       [16, 13,  8,  2],
       [20, 14, 15,  6]])

In [48]:
arr = np.arange(25)

In [54]:
ranarr = np.random.randint(0,50,10)

In [61]:
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [55]:
ranarr

array([ 3, 23, 31, 25, 19, 16, 20, 13, 38,  4])

In [52]:
arr = arr.reshape(5,5)

In [56]:
ranarr.argmax()

8

In [57]:
arr.shape

(5, 5)

In [60]:
arr.dtype

dtype('int32')

In [62]:
arr = np.arange(0,11)

In [63]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [64]:
arr[4:]

array([ 4,  5,  6,  7,  8,  9, 10])

In [65]:
arr[0:5] = 100

In [66]:
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [72]:
arr = np.arange(0,11)

In [73]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [74]:
slice_of_arr = arr[0:6]
slice_of_arr

array([0, 1, 2, 3, 4, 5])

In [75]:
slice_of_arr[:] = 99
slice_of_arr

array([99, 99, 99, 99, 99, 99])

In [77]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [78]:
arr_copy = arr.copy()

In [79]:
arr_copy

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [80]:
arr_copy[:] = 100

In [81]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [82]:
arr_copy

array([100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100])

In [67]:
arr_2d = np.array([[5,10,15],[20,25,30],[35,40,45]])

In [160]:
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [161]:
arr_2d[1:,:2]

array([[20, 25],
       [35, 40]])

In [84]:
arr = np.arange(1,6)

In [85]:
arr

array([1, 2, 3, 4, 5])

In [88]:
bool_arr = arr>3

In [89]:
arr[bool_arr]

array([4, 5])

In [90]:
arr = np.arange(0,11)

In [91]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [92]:
arr + arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [93]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [95]:
arr-arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [96]:
arr*arr

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [98]:
arr+100

array([100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110])

In [99]:
arr*2

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [100]:
arr/3

array([0.        , 0.33333333, 0.66666667, 1.        , 1.33333333,
       1.66666667, 2.        , 2.33333333, 2.66666667, 3.        ,
       3.33333333])

In [102]:
arr/arr

C:\Users\chira\AppData\Local\Temp\ipykernel_14840\1862401812.py:1: RuntimeWarning: invalid value encountered in divide
  arr/arr


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [103]:
arr ** 3

array([   0,    1,    8,   27,   64,  125,  216,  343,  512,  729, 1000],
      dtype=int32)

In [104]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766])

In [105]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [106]:
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03, 2.20264658e+04])

In [107]:
np.max(arr)

10

In [109]:
np.log(arr)

C:\Users\chira\AppData\Local\Temp\ipykernel_14840\3120950136.py:1: RuntimeWarning: divide by zero encountered in log
  np.log(arr)


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458,
       2.30258509])

In [110]:
import numpy as np

In [128]:
mylist = [5]*10

In [174]:
arr = np.ones(10) * 5

In [175]:
arr

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

In [133]:
arr = np.arange(10,51,2)

In [134]:
arr

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50])

In [135]:
arr = np.arange(0,9).reshape(3,3)

In [136]:
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [137]:
arr = np.eye(3)

In [138]:
arr

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [147]:
arr = np.random.rand(1)

In [148]:
arr

array([0.98299671])

In [176]:
arr = np.random.randn(25).reshape(5,5)

In [177]:
arr

array([[ 0.37170937, -1.58929015,  0.6000461 ,  1.02066271, -0.13326046],
       [-1.59827358,  0.96715483,  0.01493615,  1.20732548,  0.47084215],
       [-0.19275349,  0.82729808,  0.85817075,  1.28485644,  1.39540335],
       [ 0.52270919, -0.41007165,  0.7314759 , -0.96300497, -0.42028084],
       [ 0.50110014, -0.67608195,  0.00669889, -0.06496721,  0.77229906]])

In [153]:
arr = np.arange(0.01,1.01,0.01).reshape(10,10)

In [154]:
arr

array([[0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 ],
       [0.11, 0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 ],
       [0.21, 0.22, 0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 ],
       [0.31, 0.32, 0.33, 0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 ],
       [0.41, 0.42, 0.43, 0.44, 0.45, 0.46, 0.47, 0.48, 0.49, 0.5 ],
       [0.51, 0.52, 0.53, 0.54, 0.55, 0.56, 0.57, 0.58, 0.59, 0.6 ],
       [0.61, 0.62, 0.63, 0.64, 0.65, 0.66, 0.67, 0.68, 0.69, 0.7 ],
       [0.71, 0.72, 0.73, 0.74, 0.75, 0.76, 0.77, 0.78, 0.79, 0.8 ],
       [0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87, 0.88, 0.89, 0.9 ],
       [0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98, 0.99, 1.  ]])

In [155]:
arr = np.linspace(0,1,20)

In [156]:
arr

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

In [162]:
mat = np.arange(1,26).reshape(5,5)
mat

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [169]:
mat[3:,]

array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [168]:
mat[3,4]

20

In [170]:
mat.sum()

325

In [172]:
mat.std()

7.211102550927978

In [182]:
mat.sum(axis = 0)

array([55, 60, 65, 70, 75])

In [180]:
mat

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])